name       : haskell-vector
version    : 0.12.1.2
release    : 5
source     :
    - https://hackage.haskell.org/package/vector-0.12.1.2/vector-0.12.1.2.tar.gz : 3b6e27683f6f20b37b8a35d0fab9e34b57dad72ac64cb16f428726780d4011bd
license    : BSD-3-Clause
component  : programming.haskell
summary    : An efficient implementation of Int-indexed arrays (both mutable and immutable), with a powerful loop optimisation framework
description: |
    An efficient implementation of Int-indexed arrays (both mutable and immutable), with a powerful loop optimisation framework
builddeps  :
    - haskell-cabal-install
    - haskell-primitive-devel
rundeps    :
    - devel:
        - haskell-primitive-devel
networking : yes
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
