name       : haskell-vector
version    : 0.12.0.1
release    : 4
source     :
    - https://hackage.haskell.org/package/vector-0.12.0.1/vector-0.12.0.1.tar.gz : b100ee79b9da2651276278cd3e0f08a3c152505cc52982beda507515af173d7b
license    : BSD-3-Clause
component  : programming.haskell
summary    : An efficient implementation of Int-indexed arrays (both mutable and immutable), with a powerful loop optimisation framework
description: |
    An efficient implementation of Int-indexed arrays (both mutable and immutable), with a powerful loop optimisation framework
builddeps  :
    - ghc
    - haskell-cabal-install
    - haskell-primitive
setup      : |
    # Fix base requirement
    sed -i "s|4.10|4.11|g" vector.cabal
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
patterns   :
    - devel :
        - /usr/lib64/ghc-*/vector-*/include
