name       : haskell-vector
version    : 0.11.0.0
release    : 1
source     :
    - http://hackage.haskell.org/package/vector-0.11.0.0/vector-0.11.0.0.tar.gz : 0a5320ed44c3f2b04b7f61e0f63f4fcd5b337524e601e01d5813ace3f5a432e4
license    : BSD-3-Clause
component  : programming
summary    : An efficient implementation of Int-indexed arrays (both mutable and immutable), with a powerful loop optimisation framework . 
description: |
    An efficient implementation of Int-indexed arrays (both mutable and immutable), with a powerful loop optimisation framework . 
builddeps  :
    - ghc
    - haskell-primitive
setup      : |
    sudo ghc-pkg recache
    sed -i "s|4.9|4.10|g" vector.cabal
    sed -i "s|0.5|0.6|g" vector.cabal
    ghc -threaded --make Setup
    ./Setup configure --enable-shared \
                      --prefix=/usr \
                      --docdir="/usr/share/doc/\$compiler/\$pkgid" \
                      --libdir=/usr/lib64 \
                      --libsubdir="\$compiler/\$pkgid" \
                      --datadir=/usr/share \
                      --sysconfdir=/etc

build      : |
    ./Setup build
install    : |
    export GHCV=`readlink /usr/bin/ghc`
    ./Setup copy --destdir=$installdir
    ./Setup register --gen-pkg-config
    install -D -m 00644 vector-$version.conf $installdir/usr/lib64/$GHCV/package.conf.d/vector-$version.conf
    rm -f $installdir/usr/lib64/$GHCV/vector-$version/*.a
patterns   :
    - devel:
        - /usr/lib64/ghc-8.0.1/vector-0.11.0.0/include